In [12]:
import numpy as np
import pandas as pd
# rawArray = np.loadtxt('../data/vehicleinfo/imports-85.data', dtype=object ,delimiter=',')

In [17]:
df = pd.read_csv('../data/vehicleinfo/imports-85.data',delimiter=',', sep='\t', header=None)

In [24]:
df.head()

0    1            2    3    4     5            6    7      8     9   ...  \
0   3    ?  alfa-romero  gas  std   two  convertible  rwd  front  88.6  ...   
1   3    ?  alfa-romero  gas  std   two  convertible  rwd  front  88.6  ...   
2   1    ?  alfa-romero  gas  std   two    hatchback  rwd  front  94.5  ...   
3   2  164         audi  gas  std  four        sedan  fwd  front  99.8  ...   
4   2  164         audi  gas  std  four        sedan  4wd  front  99.4  ...   

    16    17    18    19    20   21    22  23  24     25  
0  130  mpfi  3.47  2.68   9.0  111  5000  21  27  13495  
1  130  mpfi  3.47  2.68   9.0  111  5000  21  27  16500  
2  152  mpfi  2.68  3.47   9.0  154  5000  19  26  16500  
3  109  mpfi  3.19  3.40  10.0  102  5500  24  30  13950  
4  136  mpfi  3.19  3.40   8.0  115  5500  18  22  17450  

[5 rows x 26 columns]

In [26]:
# 将？ 转换为None
df.replace(to_replace='?',value=np.nan,inplace=True)

In [27]:
df.head()

0    1            2    3    4     5            6    7      8     9   ...  \
0   3  NaN  alfa-romero  gas  std   two  convertible  rwd  front  88.6  ...   
1   3  NaN  alfa-romero  gas  std   two  convertible  rwd  front  88.6  ...   
2   1  NaN  alfa-romero  gas  std   two    hatchback  rwd  front  94.5  ...   
3   2  164         audi  gas  std  four        sedan  fwd  front  99.8  ...   
4   2  164         audi  gas  std  four        sedan  4wd  front  99.4  ...   

    16    17    18    19    20   21    22  23  24     25  
0  130  mpfi  3.47  2.68   9.0  111  5000  21  27  13495  
1  130  mpfi  3.47  2.68   9.0  111  5000  21  27  16500  
2  152  mpfi  2.68  3.47   9.0  154  5000  19  26  16500  
3  109  mpfi  3.19  3.40  10.0  102  5500  24  30  13950  
4  136  mpfi  3.19  3.40   8.0  115  5500  18  22  17450  

[5 rows x 26 columns]

In [42]:
# 表头建立
df.columns = ['symboling','normalized-losses','make','fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','wheel-base','length','width','height','curb-weight','engine-type','num-of-cylinders','engine-size','fuel-system','bore','stroke','compression-ratio','horsepower','peak-rpm','city-mpg','highway-mpg','price']

In [43]:
df.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3               NaN  alfa-romero       gas        std          two   
1          3               NaN  alfa-romero       gas        std          two   
2          1               NaN  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19    3.40              10.0        102      5500       24   
4         mpfi  3.19    3.40               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [52]:
# 选择部分特征值作为实验数据
data = df[['wheel-base','length','width','height','curb-weight','engine-size','bore','stroke','compression-ratio','horsepower','peak-rpm','highway-mpg']]

In [53]:
data.shape

(205, 12)

In [149]:
# 新增两条随机数据作为实验
data2 = data.copy()
# 生成随机数据
random01 = np.random.rand(data.shape[0])
random02 = np.random.rand(data.shape[0])
data2['random01']=random01
data2['random02']=random02
data2.head()

wheel-base  length  width  height  curb-weight  engine-size  bore stroke  \
0        88.6   168.8   64.1    48.8         2548          130  3.47   2.68   
1        88.6   168.8   64.1    48.8         2548          130  3.47   2.68   
2        94.5   171.2   65.5    52.4         2823          152  2.68   3.47   
3        99.8   176.6   66.2    54.3         2337          109  3.19   3.40   
4        99.4   176.6   66.4    54.3         2824          136  3.19   3.40   

   compression-ratio horsepower peak-rpm  highway-mpg  random01  random02  
0                9.0        111     5000           27  0.195826  0.267080  
1                9.0        111     5000           27  0.919615  0.193002  
2                9.0        154     5000           26  0.150425  0.247761  
3               10.0        102     5500           30  0.360847  0.245679  
4                8.0        115     5500           22  0.460136  0.882298

In [150]:
data2= data2.values
data2 = data2.astype(np.float)
# 去除Nan的行
data2=np.delete(data2,np.where(np.isnan(data2))[0],axis=0)
Y= data2[:,-3]
X = np.delete(data2, -3, 1)

In [158]:
# 归一化处理
X1 = (X1-np.mean(X1,axis=0))/np.std(X1,axis=0)
Y = (Y-np.mean(Y))/np.std(Y)
X1.shape,Y.shape

((199, 13), (199,))

In [159]:
Y.reshape((199,1))
Y.shape

(199,)

In [173]:
X1-np.std(X1,axis=0)

array([[-2.68891279, -1.42539008, -1.8317241 , ..., -1.2311026 ,
        -0.21927974,  0.3025118 ],
       [-2.68891279, -1.42539008, -1.8317241 , ..., -1.2311026 ,
        -1.36189938, -1.18855986],
       [-1.71702017, -1.23274234, -1.18680806, ..., -1.2311026 ,
        -0.93970104, -0.48056593],
       ...,
       [ 0.68800224,  0.18000771,  0.37941663, ..., -0.15908823,
        -2.18312968, -2.6003519 ],
       [ 0.68800224,  0.18000771,  0.37941663, ..., -1.65990834,
        -2.49800934,  0.17289129],
       [ 0.68800224,  0.18000771,  0.37941663, ..., -0.3734911 ,
        -1.3767783 , -0.29214034]])

r = \frac{\sum (x - m_x) (y - m_y)}
             {\sqrt{\sum (x - m_x)^2 \sum (y - m_y)^2}}

In [234]:
from scipy.stats import pearsonr
def pearsonrs(x,y):
    pears = []
    # 循环列处理
    for arr in x.T:
        pears.append(pearsonr(arr,Y)[0])
    return np.array(pears)

In [240]:
pears = np.abs(pearsonrs(X1,Y))
index = np.argsort(-pears)
pears,index

(array([0.56658047, 0.72508504, 0.68858184, 0.15241849, 0.8148516 ,
        0.72867957, 0.59532071, 0.04577927, 0.26468372, 0.77903191,
        0.0136203 , 0.08856176, 0.01223083]),
 array([ 4,  9,  5,  1,  2,  6,  0,  8,  3, 11,  7, 10, 12], dtype=int64))

In [243]:
# 选取相关系数大于0.1的，即前9个特征
X2 = X1[:,index[0:9]]
X2.shape

(199, 9)

In [249]:
# 1，分别将数据分为训练集和测试集,随机分配
X2Y = np.insert(X2,0,Y,axis=1)
X1Y= np.insert(X1,0,Y,axis=1)
# 过滤后
np.array(np.random.shuffle(X2Y))

trp = X2Y[:140,:]
tep =X2Y[140:,:]
# 原始
np.random.shuffle(X1Y)
trraw= X1Y[:140,:]
teraw= X1Y[140:,:]
trp.shape,tep.shape,trraw.shape,teraw.shape

((140, 10), (59, 10), (140, 14), (59, 14))

### 分别使用svr训练模型

In [261]:
# 三种不同的实现方式： SVR，NuSVR和LinearSVR。LinearSVR 提供的实现速度比SVR线性内核快，但仅考虑线性内核，而NuSVR实现的方式与SVR和略有不同LinearSVR。
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
# C：一个浮点数，惩罚参数
# loss：字符串。表示损失函数。可取值为
# 'hinge'：合页损失函数；
# 'squared_hinge'：合页损失函数的平方
# max_iter:一个整数，指定最大的迭代次数
# svc = svm.SVR(C=1, kernel='rbf')
regr1 = make_pipeline(StandardScaler(), SVR(C=1.0, epsilon=0.1))
regr1.fit(trp[:,1:], trp[:,0])
print(regr1.score(tep[:,1:],tep[:,0]))# 预测准确度
# 
regr2 = make_pipeline(StandardScaler(), SVR(C=1.0, epsilon=0.1))
regr2.fit(trraw[:,1:], trraw[:,0])
print(regr2.score(teraw[:,1:],teraw[:,0]))# 预测准确度

0.8144800774910517
0.7966038080153123


In [ ]:
# 比较预测准确度可以看到
# 去除权重较小特征值后，两者的准确度非常接近，证明效果不错
# 预测：
regr1.predict([[1, 1]])